name: hyperliquid
description: Hyperliquid Dart SDK for REST, WebSocket, and trading utilities (perpetuals & spot)
version: 0.0.1
repository: 
homepage: 
issue_tracker: 
topics:
  - crypto
  - trading
  - api
  - websocket
  - hyperliquid

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  crypto: ^3.0.3
  convert: ^3.1.1
  collection: ^1.1.8
  intl: ^0.19.0
  fixnum: ^1.1.0
  pointycastle: ^3.7.3
  web3dart: ^2.7.1
  msgpack_dart: ^1.0.0
  logger: ^2.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
